### ISSUE TITLE
Refresh Control

### ISSUE THREAD

**Issue by danjritter** [nunosubtil/pcf-hover-option-set#1]
In a model driven app, I'm using JavaScript to filter the available choices for a field that uses this component.  The choices filter successfully, using the native drop-down choice component the choices update, however, the choices do not update when using this component.  Is there a way to trigger the component to re render the buttons?

**Comment by nunosubtil** [comment]
Thanks for reaching out! Just to clarify, the options in the PCF Hover Option Set component are bound to the optionset field. This means the available choices are fetched from the backend, and there isn’t a direct way to modify them through frontend logic.

**Comment by danjritter** [comment]
Thanks for the quick reply!
So I've gotten it to filter on initial selection:
![image](https://github.com/user-attachments/assets/b264a688-b1e2-484b-ae8e-a733212e87b4)
![image](https://github.com/user-attachments/assets/d9cda86e-0e07-4ddf-a953-d9cbd508f0f0)
![image](https://github.com/user-attachments/assets/d54582c4-e60a-421b-a69b-a1c21bb4c45e)

Just struggling with how to trigger it to fetch the choices again if the user changes the category.

**Comment by nunosubtil** [comment]
No worries, it’s great to see someone using something I’ve created! Would you mind sharing the JavaScript code you’re using?

**Comment by danjritter** [comment]
function onCategorySelect(executionContext) {
    var formContext = executionContext.getFormContext();
    var category = formContext.getAttribute("categoryFieldLogicalName").getValue();
    var subCategory = formContext.getControl("subcategoryFieldLogicalName");

    // Clear existing options
    subCategory.clearOptions();

    // Add new options based on the selected category
    var subCategoryOptions = formContext.getAttribute("subcategoryFieldLogicalName").getOptions();
    switch (category) {
        case 188080000:
            subCategoryOptions.forEach(function(element) {
                if (element.value === 188080000 || element.value === 188080001) {
                    subCategory.addOption(element);
                }
            });
            break;
        case 188080001:
            subCategoryOptions.forEach(function(element) {
                if (element.value === 188080002 || element.value === 188080003) {
                    subCategory.addOption(element);
                }
            });
            break;
    }
}

**Comment by nunosubtil** [comment]
Could you please clarify which event the script is running on? For example, is it onSave, onLoad, or onChange?

**Comment by danjritter** [comment]
It's running in the onChange, the intent is to filter the subcategory based on the selected category.  On initial selection it behaves as expected, but should the user change the category, it doesn't change the buttons displayed.

**Comment by nunosubtil** [comment]
Have you tried forcing a refresh in either the form or the field itself? E.g., “formContext.data.refresh();", “subCategoryOptions.refresh();”

**Comment by danjritter** [comment]
I have, so far I've tried toggling the visibility, requesting the control render, refresh, and the formcontext refresh.  Does the control itself contain a refresh function that can be accessed?

**Comment by nunosubtil** [comment]
I hadn’t contemplated that scenario when building the PCF, so it doesn’t have a refresh function that can be accessed externally. If the solutions we discussed earlier didn’t work, I’m afraid I don’t see a viable option that doesn’t involve updating the PCF itself.

Feel free to open a pull request, and we can work on implementing that feature.

**Comment by danjritter** [comment]
You're awesome.  I really appreciate your help, and for the record I love what you've built.  To get me across the finish line today I implemented radio buttons instead:
https://github.com/JPkenpachi1/PCF_Components
![2024-10-04_11-42-10](https://github.com/user-attachments/assets/c909ca01-9ffd-49ac-86df-adfa1286d2c6)

**Comment by nunosubtil** [comment]
Thank you very much! If you have any questions or need assistance, feel free to reach out anytime.
